// styles/GlobalStyle.js
import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const CARD_SIZE_SINGLE = (width - 80) / 5;
const CARD_SIZE_PAIR = (width - 80) / 5;
const CARD_SIZE_TRIO = (width - 80) / 5;
const BTN_SIZE_DIGIT = (width - 80) / 5;

// Consolidated Global Styles
export const globalStyleFunc = StyleSheet.create({
    mainContainer: {
        flex: 1,
        paddingTop: 40,
    },

    // Header Canvas Styling Setup
    headerWrapper: { width: "100%", backgroundColor: "#000" },
    headerGradient: { paddingVertical: 14 },
    headerRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 16,
        position: "relative",
    },
    logoBadgeContainer: { position: "absolute", left: 20 },
    logoOuterGear: {
        width: 38,
        height: 38,
        borderRadius: 19,
        borderWidth: 2,
        borderColor: "#EBB828",
        alignItems: "center",
        justifyContent: "center",
        borderStyle: "dashed",
    },
    logoInnerStarProfile: {
        width: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: "#EBB828",
        alignItems: "center",
        justifyContent: "center",
    },
    logoStarSymbol: { color: "#5E0004", fontSize: 14, fontWeight: "bold" },
    logoTitleText: {
        color: "#FFF5C2",
        fontSize: 30,
        fontWeight: "900",
        letterSpacing: 1.5,
        textShadowColor: "rgba(0,0,0,0.8)",
        textShadowOffset: { width: 1, height: 2 },
        textShadowRadius: 4,
    },
    walletContainer: { position: "absolute", right: 20 },
    walletArcTrack: {
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 2,
        borderColor: "#EBB828",
        borderRadius: 16,
        paddingHorizontal: 10,
        paddingVertical: 1,
        backgroundColor: "rgba(0,0,0,0.4)",
    },
    walletCurrencySymbol: {
        color: "#FFF5C2",
        fontSize: 16,
        fontWeight: "900",
        marginRight: 3,
    },
    walletBalanceAmount: { color: "#FFF5C2", fontSize: 18, fontWeight: "900" },
    headerArchBar: { height: 3.5, width: "100%" },

    // Inner Main Layout Framework
    body: {
        flex: 1,
        paddingHorizontal: 10,
        paddingTop: 14,
        backgroundColor: "#000000",
    },
    outerBoardFrame: {
        flex: 1,
        borderWidth: 3,
        borderColor: "#D4AF37",
        borderRadius: 24,
        backgroundColor: "#0F0F0F",
        overflow: "hidden",
        padding: 6,
    },
    boardHeaderRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        paddingVertical: 10,
    },
    boardHeaderIcon: { fontSize: 13 },
    boardHeaderStar: { color: "#D4AF37", fontSize: 11 },
    boardHeaderTitle: {
        color: "#D4AF37",
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 0.5,
    },

    scrollContent: { paddingBottom: 10 },

    // Row Component Definitions
    cardOuter: {
        marginBottom: 10,
        borderRadius: 16,
        overflow: "hidden",
        borderWidth: 1.5,
        borderColor: "#333333",
    },
    cardGradient: { borderRadius: 16 },
    cardTouchRow: { flexDirection: "row", padding: 8, alignItems: "center" },

    // Left Side Rounded Corner Badge Frame Configuration Block
    medalCardOuterFrame: {
        borderRadius: 16,
        overflow: "hidden",
        borderWidth: 1.5,
        borderColor: "#D4AF37",
    },
    medalCardContainer: {
        width: 96,
        height: 96,
        borderRadius: 14,
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
        overflow: "hidden",
    },
    sunburstContainer: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: "center",
        alignItems: "center",
        opacity: 0.12,
    },
    sunburstRay: {
        position: "absolute",
        width: 2,
        height: 130,
        backgroundColor: "#FFFFFF",
    },

    medalWrap: {
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
        width: 74,
        height: 74,
    },
    medalOuterRing: {
        width: 64,
        height: 64,
        borderRadius: 32,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 5,
    },
    medalMidRing: {
        width: 58,
        height: 58,
        borderRadius: 29,
        alignItems: "center",
        justifyContent: "center",
    },
    medalInnerRing: {
        width: 52,
        height: 52,
        borderRadius: 26,
        alignItems: "center",
        justifyContent: "center",
    },
    medalFace: {
        width: 46,
        height: 46,
        borderRadius: 23,
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
        overflow: "hidden",
    },
    medalStar: {
        position: "absolute",
        color: "#FFF5C2",
        fontSize: 6,
        opacity: 0.95,
    },

    // Half Shape Transparent Overlay Mask Mirroring Glass shine Reflection
    glassShineTopOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        height: 20,
        backgroundColor: "rgba(255,255,255,0.22)",
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
    },
    medalRewardText: {
        color: "#FFF5C2",
        fontWeight: "900",
        fontSize: 16,
        textShadowColor: "#000",
        textShadowRadius: 3,
        marginTop: 1,
        zIndex: 10,
    },

    // 2 Distinct Ribbon Ribbon Banner Tails Tucked Beneath Circle Layer
    ribbonTail: {
        position: "absolute",
        bottom: -1,
        width: 12,
        height: 14,
        backgroundColor: "#AA820A",
        borderWidth: 1,
        borderColor: "#D4AF37",
        zIndex: 1,
    },
    ribbonLeftTail: {
        left: 18,
        transform: [{ rotate: "-18deg" }],
    },
    ribbonRightTail: {
        right: 18,
        transform: [{ rotate: "18deg" }],
    },

    // Typography Right Context Configurations
    infoSection: { flex: 1, paddingLeft: 12, justifyContent: "center" },
    titleRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    gameName: {
        fontSize: 14,
        fontWeight: "800",
        color: "#FFFFFF",
        letterSpacing: 0.3,
    },
    actionBadge: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: "#2D2D2D",
        alignItems: "center",
        justifyContent: "center",
    },
    actionBadgeText: { color: "#888888", fontSize: 11 },
    gameSubTitle: {
        fontSize: 11,
        color: "#777777",
        marginVertical: 1,
        fontWeight: "700",
    },
    metaText: {
        fontSize: 13,
        color: "#FFFFFF",
        fontWeight: "800",
        marginTop: 12,
    },
    cardFooterMetrics: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 4,
    },
    footerLabelLeft: {
        color: "#D4AF37",
        fontSize: 11,
        fontWeight: "800",
    },
    footerLabelRight: {
        color: "#D4AF37",
        fontSize: 11,
        fontWeight: "800",
    },

    // ContestPoolScreen Specific Styles
    poolHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: "#0d0d0d",
    },
    poolBackButton: {
        width: 40,
        height: 40,
        justifyContent: "center",
        alignItems: "center",
    },
    poolBackButtonText: {
        color: "#fff",
        fontSize: 24,
        fontWeight: "bold",
    },
    poolHeaderTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#fff",
    },
    poolPlaceholder: {
        width: 40,
    },
    poolListContainer: {
        padding: 16,
    },
    poolCardContainer: {
        marginBottom: 16,
        borderRadius: 12,
        overflow: "hidden",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    poolCard: {
        flexDirection: "row",
        padding: 16,
        alignItems: "center",
        minHeight: 120,
    },
    poolLeftSection: {
        alignItems: "center",
        marginRight: 12,
    },
    poolIconContainer: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 4,
    },
    poolIconText: {
        fontSize: 24,
    },
    poolNameText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "bold",
    },
    poolMiddleSection: {
        flex: 1,
        marginRight: 12,
    },
    poolDetailRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 6,
    },
    poolDetailLabel: {
        color: "rgba(255, 255, 255, 0.8)",
        fontSize: 12,
    },
    poolDetailValue: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "bold",
    },
    poolWinPrize: {
        color: "#FFD700",
        fontSize: 16,
        fontWeight: "bold",
    },
    poolSlotsContainer: {
        marginTop: 8,
    },
    poolSlotsInfo: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 4,
    },
    poolSlotsLabel: {
        color: "rgba(255, 255, 255, 0.8)",
        fontSize: 11,
    },
    poolSlotsValue: {
        color: "#fff",
        fontSize: 11,
        fontWeight: "600",
    },
    poolProgressBarContainer: {
        height: 6,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        borderRadius: 3,
        overflow: "hidden",
    },
    poolProgressBarFill: {
        height: "100%",
        backgroundColor: "#FFD700",
        borderRadius: 3,
    },
    poolJoinButton: {
        backgroundColor: "#fff",
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 8,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    poolJoinButtonText: {
        color: "#0d0d0d",
        fontSize: 14,
        fontWeight: "bold",
    },
});

// HowToPlay Screen Styles
export const howToPlayStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#2E0002" },
    gradient: { flex: 1 },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 12,
    },
    circularBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#5E0004',
        borderWidth: 1.5,
        borderColor: '#D4AF37',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.35,
        shadowRadius: 2.5,
        elevation: 3,
    },
    balanceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    balancePill: {
        height: 32,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: '#D4AF37',
        backgroundColor: '#3A0002',
        paddingHorizontal: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1.5 },
        shadowOpacity: 0.25,
        shadowRadius: 2,
        elevation: 2,
    },
    balanceLabel: {
        color: '#D4AF37',
        fontSize: 7,
        fontWeight: 'bold',
        letterSpacing: 0.5,
        textTransform: 'uppercase',
    },
    balanceText: {
        color: '#ffffff',
        fontSize: 11,
        fontWeight: '900',
    },
    scrollArea: {
        flex: 1,
        position: 'relative',
        marginHorizontal: 16,
        marginTop: 10,
        marginBottom: 16,
    },
    scrollRollerTop: {
        height: 24,
        width: '100%',
        position: 'absolute',
        top: 0,
        zIndex: 15,
        borderRadius: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 2,
        elevation: 4,
    },
    scrollRollerBottom: {
        height: 24,
        width: '100%',
        position: 'absolute',
        bottom: 0,
        zIndex: 15,
        borderRadius: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.25,
        shadowRadius: 2,
        elevation: 4,
    },
    rollerCapLeft: {
        width: 14,
        height: 24,
        borderTopLeftRadius: 6,
        borderBottomLeftRadius: 6,
        backgroundColor: '#E0A926',
        position: 'absolute',
        left: -10,
        borderWidth: 1,
        borderColor: '#FFF0AC',
    },
    rollerCapRight: {
        width: 14,
        height: 24,
        borderTopRightRadius: 6,
        borderBottomRightRadius: 6,
        backgroundColor: '#E0A926',
        position: 'absolute',
        right: -10,
        borderWidth: 1,
        borderColor: '#FFF0AC',
    },
    parchmentSheet: {
        flex: 1,
        backgroundColor: '#F5E6CC',
        borderLeftWidth: 1.5,
        borderRightWidth: 1.5,
        borderColor: '#DCC09B',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
        paddingHorizontal: 14,
        marginTop: 11,
        marginBottom: 11,
    },
    scrollContent: {
        paddingTop: 18,
        paddingBottom: 20,
    },
    title: {
        color: '#4E2C0F',
        fontSize: 22,
        fontWeight: '900',
        textAlign: 'center',
        letterSpacing: 1.5,
        marginBottom: 16,
    },
    stepCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#61321C',
        borderWidth: 1.2,
        borderColor: '#8E5133',
        borderRadius: 10,
        padding: 10,
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1.5 },
        shadowOpacity: 0.2,
        shadowRadius: 1.5,
        elevation: 2,
    },
    stepRankCircle: {
        width: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: '#2E150B',
        borderWidth: 1,
        borderColor: '#8E5133',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    stepRankText: {
        color: '#D4AF37',
        fontSize: 12,
        fontWeight: 'bold',
    },
    stepIllustrationContainer: {
        width: 52,
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    stepIllustrationText: {
        fontSize: 26,
    },
    mockCardsWrap: {
        flexDirection: 'row',
        width: 52,
        height: 44,
        position: 'relative',
        alignItems: 'center',
        justifyContent: 'center',
    },
    miniCard: {
        width: 22,
        height: 32,
        borderRadius: 4,
        backgroundColor: '#ffffff',
        borderWidth: 0.8,
        borderColor: '#DCC09B',
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.15,
        shadowRadius: 1,
        elevation: 1,
    },
    miniCardValue: {
        fontSize: 8,
        fontWeight: 'bold',
        lineHeight: 9,
    },
    miniCardSuit: {
        fontSize: 9,
        lineHeight: 10,
        marginTop: -1,
    },
    stepTextCol: {
        flex: 1,
    },
    stepTitle: {
        color: '#D5A754',
        fontSize: 13,
        fontWeight: 'bold',
        marginBottom: 1,
    },
    stepDesc: {
        color: '#F2D3B8',
        fontSize: 10,
        lineHeight: 14,
    },
    goldButton: {
        width: '65%',
        alignSelf: 'center',
        borderRadius: 22,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2.5 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        elevation: 4,
        marginTop: 12,
    },
    goldButtonGradient: {
        paddingVertical: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    goldButtonText: {
        color: '#3A2002',
        fontSize: 15,
        fontWeight: '900',
        letterSpacing: 1,
    },
});

// Single Card Screen Styles
export const singleCardStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#2E0002", paddingTop: 45 },
    gradient: { flex: 1 },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(255,168,0,0.3)",
    },
    backButton: { color: "#FFA800", fontSize: 16, fontWeight: "600" },
    headerTitle: { fontSize: 18, fontWeight: "bold", color: "#FFA800" },
    coinBalance: {
        backgroundColor: "rgba(255,168,0,0.15)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
    },
    coinText: { color: "#FFD700", fontWeight: "bold", fontSize: 13 },
    infoBar: {
        flexDirection: "row",
        justifyContent: "space-around",
        paddingVertical: 14,
        backgroundColor: "rgba(0,0,0,0.4)",
    },
    infoItem: { alignItems: "center" },
    infoLabel: {
        color: "rgba(255,255,255,0.5)",
        fontSize: 10,
        fontWeight: "600",
    },
    infoValue: { color: "#fff", fontSize: 17, fontWeight: "bold", marginTop: 3 },
    gameArea: { flex: 1, paddingHorizontal: 20, paddingTop: 28 },
    instruction: {
        fontSize: 22,
        fontWeight: "bold",
        color: "#FFA800",
        textAlign: "center",
        marginBottom: 28,
        letterSpacing: 1,
    },
    cardsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        rowGap: 12,
    },
    card: { borderRadius: 8, overflow: "hidden", elevation: 4 },
    selectedCard: {
        transform: [{ scale: 1.1 }],
        shadowColor: "#FFA800",
        shadowOpacity: 0.9,
        shadowRadius: 10,
        elevation: 12,
    },
    cardInner: { flex: 1, justifyContent: "center", alignItems: "center" },
    cardValue: { fontSize: 18, fontWeight: "bold" },
    cardSuit: { fontSize: 20 },
    betInfo: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 28,
        paddingVertical: 14,
        backgroundColor: "rgba(255,168,0,0.1)",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(255,168,0,0.3)",
    },
    betInfoText: { color: "#FFA800", fontSize: 14, fontWeight: "bold" },
    placeBetButton: {
        margin: 20,
        borderRadius: 25,
        overflow: "hidden",
        elevation: 5,
    },
    disabledButton: { opacity: 0.5 },
    buttonGradient: {
        paddingVertical: 18,
        alignItems: "center"
    },
    placeBetText: {
        color: "#1a0203",
        fontSize: 17,
        fontWeight: "bold",
        letterSpacing: 1,
    },
});

// Pair Selection Screen Styles
export const pairSelectionStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#001a2d" },
    gradient: { flex: 1 },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(6,182,212,0.3)",
    },
    backButton: { color: "#06B6D4", fontSize: 16, fontWeight: "600" },
    headerTitle: { fontSize: 18, fontWeight: "bold", color: "#06B6D4" },
    coinBalance: {
        backgroundColor: "rgba(6,182,212,0.15)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
    },
    coinText: { color: "#FFD700", fontWeight: "bold", fontSize: 13 },
    infoBar: {
        flexDirection: "row",
        justifyContent: "space-around",
        paddingVertical: 14,
        backgroundColor: "rgba(0,0,0,0.4)",
    },
    infoItem: { alignItems: "center" },
    infoLabel: {
        color: "rgba(255,255,255,0.5)",
        fontSize: 10,
        fontWeight: "600",
    },
    infoValue: { color: "#fff", fontSize: 17, fontWeight: "bold", marginTop: 3 },
    gameArea: { flex: 1, paddingHorizontal: 20, paddingTop: 24 },
    instruction: {
        fontSize: 22,
        fontWeight: "bold",
        color: "#06B6D4",
        textAlign: "center",
        marginBottom: 6,
        letterSpacing: 1,
    },
    subInstruction: {
        color: "rgba(255,255,255,0.5)",
        fontSize: 13,
        textAlign: "center",
        marginBottom: 22,
    },
    cardsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        rowGap: 12,
    },
    card: { borderRadius: 8, overflow: "hidden", elevation: 4 },
    selectedCard: {
        transform: [{ scale: 1.1 }],
        shadowColor: "#06B6D4",
        shadowOpacity: 0.9,
        shadowRadius: 10,
        elevation: 12,
    },
    cardInner: { flex: 1, justifyContent: "center", alignItems: "center" },
    cardValue: { fontSize: 18, fontWeight: "bold" },
    cardSuit: { fontSize: 20 },
    betInfo: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 24,
        paddingVertical: 14,
        backgroundColor: "rgba(6,182,212,0.1)",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(6,182,212,0.3)",
    },
    betInfoText: { color: "#06B6D4", fontSize: 14, fontWeight: "bold" },
    placeBetButton: {
        margin: 20,
        borderRadius: 25,
        overflow: "hidden",
        elevation: 5,
    },
    disabledButton: { opacity: 0.5 },
    buttonGradient: { paddingVertical: 18, alignItems: "center" },
    placeBetText: {
        color: "#fff",
        fontSize: 17,
        fontWeight: "bold",
        letterSpacing: 1,
    },
});

// Trio Game Screen Styles
export const trioStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#1a0a2e" },
    gradient: { flex: 1 },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(139,92,246,0.3)",
    },
    backButton: { color: "#8B5CF6", fontSize: 16, fontWeight: "600" },
    headerTitle: { fontSize: 18, fontWeight: "bold", color: "#8B5CF6" },
    coinBalance: {
        backgroundColor: "rgba(139,92,246,0.15)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
    },
    coinText: { color: "#FFD700", fontWeight: "bold", fontSize: 13 },
    infoBar: {
        flexDirection: "row",
        justifyContent: "space-around",
        paddingVertical: 14,
        backgroundColor: "rgba(0,0,0,0.4)",
    },
    infoItem: { alignItems: "center" },
    infoLabel: {
        color: "rgba(255,255,255,0.5)",
        fontSize: 10,
        fontWeight: "600",
    },
    infoValue: { fontSize: 17, fontWeight: "bold", marginTop: 3 },
    gameArea: { flex: 1, paddingHorizontal: 20, paddingTop: 20 },
    instruction: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#8B5CF6",
        textAlign: "center",
        letterSpacing: 2,
        marginBottom: 10,
    },
    starsRow: {
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 12,
        gap: 10,
    },
    star: { fontSize: 26, color: "rgba(255,255,255,0.2)" },
    starActive: { color: "#FFD700" },
    tripleTag: {
        alignSelf: "center",
        borderWidth: 1,
        borderRadius: 20,
        paddingHorizontal: 20,
        paddingVertical: 6,
        marginBottom: 12,
        backgroundColor: "rgba(255,255,255,0.05)",
    },
    tripleTagText: { fontWeight: "bold", fontSize: 14 },
    cardsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        rowGap: 10,
    },
    card: { borderRadius: 8, overflow: "hidden", elevation: 4 },
    selectedCard: {
        transform: [{ scale: 1.08 }],
        shadowColor: "#8B5CF6",
        shadowOpacity: 0.9,
        shadowRadius: 10,
        elevation: 12,
    },
    cardInner: { flex: 1, justifyContent: "center", alignItems: "center" },
    cardValue: { fontSize: 18, fontWeight: "bold" },
    cardSuit: { fontSize: 20 },
    betInfo: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginTop: 18,
        paddingVertical: 12,
        backgroundColor: "rgba(139,92,246,0.1)",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(139,92,246,0.3)",
    },
    betInfoText: { color: "#8B5CF6", fontSize: 14, fontWeight: "bold" },
    placeBetButton: {
        margin: 20,
        borderRadius: 25,
        overflow: "hidden",
        elevation: 5,
    },
    disabledButton: { opacity: 0.5 },
    buttonGradient: { paddingVertical: 18, alignItems: "center" },
    placeBetText: {
        color: "#fff",
        fontSize: 17,
        fontWeight: "bold",
        letterSpacing: 1,
    },
});

// Last Digit Sum Screen Styles
export const lastDigitSumStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#0a1628" },
    gradient: { flex: 1 },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(249,115,22,0.3)",
    },
    backButton: { color: "#F97316", fontSize: 16, fontWeight: "600" },
    headerTitle: { fontSize: 18, fontWeight: "bold", color: "#F97316" },
    coinBalance: {
        backgroundColor: "rgba(249,115,22,0.15)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
    },
    coinText: { color: "#FFD700", fontWeight: "bold", fontSize: 13 },
    infoBar: {
        flexDirection: "row",
        justifyContent: "space-around",
        paddingVertical: 14,
        backgroundColor: "rgba(0,0,0,0.4)",
    },
    infoItem: { alignItems: "center" },
    infoLabel: {
        color: "rgba(255,255,255,0.5)",
        fontSize: 10,
        fontWeight: "600",
    },
    infoValue: { fontSize: 17, fontWeight: "bold", marginTop: 3 },
    gameArea: { flex: 1, paddingHorizontal: 20, paddingTop: 20 },
    titleBox: {
        backgroundColor: "rgba(0,0,0,0.4)",
        borderRadius: 12,
        padding: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: "rgba(249,115,22,0.2)",
        alignItems: "center",
    },
    instruction: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#fff",
        letterSpacing: 2,
        marginBottom: 6,
    },
    subInstruction: {
        fontSize: 13,
        color: "rgba(255,255,255,0.6)",
        textAlign: "center",
    },
    digitsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-around",
        marginBottom: 20,
    },
    digitInner: { flex: 1, justifyContent: "center", alignItems: "center" },
    digitInactive: {
        backgroundColor: "rgba(255,255,255,0.07)",
        borderWidth: 1.5,
        borderColor: "rgba(249,115,22,0.3)",
    },
    digitText: {
        fontSize: 26,
        fontWeight: "bold",
        color: "rgba(255,255,255,0.8)",
    },
    exampleBox: {
        backgroundColor: "rgba(249,115,22,0.08)",
        borderRadius: 10,
        padding: 12,
        alignItems: "center",
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "rgba(249,115,22,0.2)",
    },
    exampleLabel: {
        color: "#F97316",
        fontWeight: "bold",
        fontSize: 11,
        marginBottom: 4,
    },
    exampleText: { color: "rgba(255,255,255,0.6)", fontSize: 13 },
    betInfo: {
        flexDirection: "row",
        justifyContent: "space-around",
        paddingVertical: 12,
        backgroundColor: "rgba(249,115,22,0.1)",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(249,115,22,0.3)",
    },
    betInfoText: { color: "#F97316", fontSize: 14, fontWeight: "bold" },
    placeBetButton: {
        margin: 20,
        borderRadius: 25,
        overflow: "hidden",
        elevation: 5,
    },
    disabledButton: { opacity: 0.5 },
    buttonGradient: { paddingVertical: 18, alignItems: "center" },
    placeBetText: {
        color: "#fff",
        fontSize: 17,
        fontWeight: "bold",
        letterSpacing: 1,
    },
});

// Jackpot Screen Styles
export const jackpotStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#1a0800" },
    gradient: { flex: 1 },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(255,165,0,0.3)",
    },
    backButton: { color: "#FFD700", fontSize: 16, fontWeight: "600" },
    headerTitle: {
        fontSize: 22,
        fontWeight: "bold",
        color: "#FFD700",
        letterSpacing: 3,
    },
    coinBalance: {
        backgroundColor: "rgba(255,215,0,0.15)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
    },
    coinText: { color: "#FFD700", fontWeight: "bold", fontSize: 13 },
    potSection: {
        alignItems: "center",
        paddingVertical: 28,
        paddingHorizontal: 20,
    },
    potIcon: { fontSize: 80 },
    jackpotLabel: {
        fontSize: 28,
        fontWeight: "bold",
        color: "#FFD700",
        letterSpacing: 3,
        marginTop: 4,
    },
    prizePoolLabel: {
        color: "rgba(255,255,255,0.6)",
        fontSize: 13,
        marginTop: 8,
    },
    prizeAmount: { fontSize: 46, fontWeight: "bold", color: "#FFD700" },
    winnerTag: {
        backgroundColor: "rgba(255,215,0,0.15)",
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: "rgba(255,215,0,0.3)",
        marginTop: 8,
    },
    winnerTagText: { color: "#FFD700", fontWeight: "600", fontSize: 13 },
    section: {
        marginHorizontal: 20,
        marginBottom: 16,
        backgroundColor: "rgba(0,0,0,0.4)",
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: "rgba(255,215,0,0.15)",
    },
    sectionTitle: {
        color: "#FFD700",
        fontWeight: "bold",
        fontSize: 15,
        marginBottom: 12,
    },
    card: {
        width: 60,
        height: 88,
        borderRadius: 8,
        overflow: "hidden",
        marginHorizontal: 5,
        elevation: 3,
    },
    selectedCard: {
        transform: [{ scale: 1.1 }],
        shadowColor: "#FFD700",
        shadowOpacity: 0.9,
        shadowRadius: 8,
        elevation: 10,
    },
    cardInner: { flex: 1, justifyContent: "center", alignItems: "center" },
    cardValue: { fontSize: 20, fontWeight: "bold" },
    cardSuit: { fontSize: 18 },
    amountInputRow: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255,255,255,0.05)",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "rgba(255,215,0,0.3)",
        paddingHorizontal: 16,
        marginBottom: 12,
    },
    rupeeSign: {
        color: "#FFD700",
        fontSize: 22,
        fontWeight: "bold",
        marginRight: 6,
    },
    amountInput: {
        flex: 1,
        color: "#fff",
        fontSize: 22,
        fontWeight: "bold",
        paddingVertical: 12,
    },
    quickAmounts: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        marginBottom: 10,
    },
    quickBtn: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: "rgba(255,255,255,0.07)",
        borderWidth: 1,
        borderColor: "rgba(255,215,0,0.25)",
    },
    quickBtnActive: {
        backgroundColor: "rgba(255,215,0,0.2)",
        borderColor: "#FFD700",
    },
    quickBtnText: {
        color: "rgba(255,255,255,0.6)",
        fontSize: 13,
        fontWeight: "600",
    },
    quickBtnTextActive: { color: "#FFD700" },
    minNote: {
        color: "rgba(255,255,255,0.35)",
        fontSize: 12,
        textAlign: "center",
    },
    placeBetButton: {
        marginHorizontal: 20,
        marginBottom: 30,
        borderRadius: 25,
        overflow: "hidden",
        elevation: 5,
    },
    disabledButton: { opacity: 0.5 },
    buttonGradient: { paddingVertical: 20, alignItems: "center" },
    placeBetText: {
        color: "#1a0800",
        fontSize: 20,
        fontWeight: "bold",
        letterSpacing: 2,
    },
});

// Live Game Screen Styles
export const liveGameStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#1a0000" },
    gradient: { flex: 1 },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 12,
    },
    headerTitle: {
        color: "#FFD700",
        fontWeight: "bold",
        fontSize: 13,
        letterSpacing: 2,
    },
    timerBadge: {
        backgroundColor: "rgba(0,0,0,0.5)",
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: "#FFD700",
    },
    timerText: { color: "#FFD700", fontSize: 18, fontWeight: "bold" },
    coinBalance: {
        backgroundColor: "rgba(255,215,0,0.12)",
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 12,
    },
    coinText: { color: "#FFD700", fontWeight: "bold", fontSize: 12 },
    statusText: {
        color: "#FFD700",
        textAlign: "center",
        fontSize: 15,
        fontWeight: "bold",
        letterSpacing: 2,
        marginBottom: 6,
    },
    arena: { width: "100%", position: "relative" },
    playerAvatar: {
        width: 58,
        height: 58,
        borderRadius: 29,
        backgroundColor: "rgba(255,255,255,0.08)",
        borderWidth: 2,
        borderColor: "rgba(255,215,0,0.3)",
        justifyContent: "center",
        alignItems: "center",
    },
    playerAvatarYou: {
        borderColor: "#FFD700",
        backgroundColor: "rgba(255,215,0,0.12)",
    },
    avatarEmoji: { fontSize: 22 },
    betBadge: {
        position: "absolute",
        bottom: -2,
        right: -2,
        backgroundColor: "#FFD700",
        borderRadius: 9,
        paddingHorizontal: 4,
        paddingVertical: 1,
    },
    betBadgeText: { color: "#1a0000", fontWeight: "bold", fontSize: 9 },
    cardWrap: {
        position: "absolute",
        left: width / 2 - 80,
        alignItems: "center",
        justifyContent: "center",
    },
    cardGlow: {
        position: "absolute",
        width: 200,
        height: 240,
        borderRadius: 20,
        backgroundColor: "#FFD700",
        shadowColor: "#FFD700",
        shadowRadius: 40,
        shadowOpacity: 1,
    },
    mainCard: {
        width: 150,
        height: 210,
        borderRadius: 16,
        justifyContent: "center",
        alignItems: "center",
        elevation: 20,
    },
    cardValueLarge: { fontSize: 64, fontWeight: "bold", color: "#cc0000" },
    cardSuitLarge: { fontSize: 52, color: "#cc0000" },
    cardBack: { alignItems: "center" },
    revealingLabel: {
        color: "#333",
        fontSize: 13,
        fontWeight: "bold",
        textAlign: "center",
        marginBottom: 4,
    },
    cardBackText: { fontSize: 70, fontWeight: "bold", color: "#222" },
    betStrip: {
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        margin: 16,
        paddingVertical: 16,
        paddingHorizontal: 20,
        backgroundColor: "rgba(0,0,0,0.6)",
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(255,215,0,0.15)",
    },
    betStripItem: { alignItems: "center" },
    betStripLabel: {
        color: "rgba(255,255,255,0.45)",
        fontSize: 10,
        marginBottom: 4,
    },
    betStripValue: { color: "#fff", fontWeight: "bold", fontSize: 16 },
    betStripDivider: {
        width: 1,
        height: 30,
        backgroundColor: "rgba(255,255,255,0.1)",
    },
});

// Wallet Screen Styles
export const walletStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#2E0002" },
    gradient: { flex: 1 },
    scrollContent: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        paddingBottom: 40,
    },

    // Header Layout matching mockup
    headerTopRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
        marginBottom: 8,
    },
    headerLeftButton: {
        padding: 4,
        minWidth: 44,
    },
    menuLine1: {
        width: 20,
        height: 2.5,
        backgroundColor: "#ffffff",
        marginBottom: 4,
        borderRadius: 1.25,
    },
    menuLine2: {
        width: 14,
        height: 2.5,
        backgroundColor: "#ffffff",
        borderRadius: 1.25,
    },
    headerTitleText: {
        color: "#FFA800",
        fontSize: 20,
        fontWeight: "900",
        letterSpacing: 1.5,
        textAlign: "center",
        flex: 1,
    },
    balanceContainer: {
        alignItems: "center",
        marginVertical: 12,
        width: "100%",
    },
    headerSubTitleText: {
        color: "rgba(255, 255, 255, 0.4)",
        fontSize: 25,
        fontWeight: "600",
        letterSpacing: 0.5,
        marginBottom: 4,
        textAlign: "center",
    },
    myWalletLabel: {
        color: "#ffffff",
        fontSize: 26,
        fontWeight: "bold",
        textAlign: "center",
        marginBottom: 6,
        marginTop: 4,
    },
    matkaHeaderLogo: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
    matkaHeaderCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: "#ffffff",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 8,
        borderBottomLeftRadius: 4, // bubble tip styling
    },
    matkaHeaderCircleText: {
        color: "#2E0002", // matches maroon red background theme
        fontSize: 18,
        fontWeight: "900",
    },
    matkaHeaderTextBlock: {
        flexDirection: "column",
        justifyContent: "center",
    },
    matkaHeaderSubText: {
        color: "#ffffff",
        fontSize: 7,
        fontWeight: "bold",
        letterSpacing: 1.2,
        lineHeight: 8,
        textTransform: "uppercase",
    },
    matkaHeaderWhiteText: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "bold",
        lineHeight: 16,
    },
    matkaHeaderGoldText: {
        color: "#ffffff",
        fontSize: 10,
        fontWeight: "bold",
        letterSpacing: 0.5,
        lineHeight: 12,
        textTransform: "uppercase",
        marginTop: -1,
    },
    headerBalanceText: {
        color: "#FFB700",
        fontSize: 56,
        fontWeight: "900",
        letterSpacing: 0.5,
        textAlign: "center",
    },
    gradientTextMask: {
        height: 70,
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
    },
    gradientTextElement: {
        backgroundColor: "transparent",
        textAlign: "center",
        width: "100%",
    },

    // Coin Stack Custom Visual
    coinStackContainer: {
        width: 44,
        height: 44,
        justifyContent: "center",
        alignItems: "center",
    },
    coinStackWrapper: {
        width: 32,
        height: 32,
        position: "relative",
    },
    coinLayer: {
        position: "absolute",
        left: 0,
        width: 32,
        height: 10,
        borderRadius: 5,
        borderWidth: 1.5,
    },

    // Matka Gaming Custom Visual
    logoBadgeContainer: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        alignItems: "center",
        justifyContent: "center",
        minWidth: 44,
    },
    logoBadgeCrownContainer: {
        marginBottom: -2,
    },
    logoBadgeCrown: {
        fontSize: 10,
        color: "#FFA800",
    },
    logoRightText: {
        color: "#FFA800",
        fontSize: 9,
        fontWeight: "900",
        letterSpacing: 0.5,
        textTransform: "uppercase",
    },
    logoRightSubText: {
        color: "#FFA800",
        fontSize: 7,
        fontWeight: "800",
        letterSpacing: 0.3,
        textTransform: "uppercase",
        marginTop: -2,
    },

    // Action Cards (Side-by-Side)
    cardsContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 10,
        marginBottom: 16,
    },
    card: {
        flex: 1,
        borderRadius: 20,
        padding: 14,
        minHeight: 230,
        position: "relative",
        overflow: "hidden",
    },
    cardGreen: {},
    cardOrange: {},
    cardSunburstContainer: {
        position: "absolute",
        top: 55, // Centered behind the badge icon
        left: "50%",
        width: 0,
        height: 0,
        justifyContent: "center",
        alignItems: "center",
    },
    cardSunburstRay: {
        position: "absolute",
        width: 2.2,
        height: 350,
    },
    cardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 4,
    },
    cardHeaderLeft: {
        flexDirection: "column",
    },
    cardHeaderLabel1: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "bold",
    },
    cardHeaderLabel2Green: {
        color: "rgba(255, 255, 255, 0.7)",
        fontSize: 9,
        marginTop: 1,
    },
    cardHeaderLabel2Orange: {
        color: "rgba(255, 255, 255, 0.7)",
        fontSize: 9,
        marginTop: 1,
    },
    cardBadgeContainer: {
        alignSelf: "center",
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: "#ffffff",
        justifyContent: "center",
        alignItems: "center",
        marginVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
        zIndex: 2,
    },
    cardLabel: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "700",
        textAlign: "center",
        marginTop: 2,
        zIndex: 2,
    },
    cardAmount: {
        color: "#fff",
        fontSize: 20,
        fontWeight: "900",
        textAlign: "center",
        marginVertical: 4,
        zIndex: 2,
    },
    cardButton: {
        width: "100%",
        paddingVertical: 9,
        borderRadius: 25,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.15)",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 8,
        zIndex: 2,
    },
    cardButtonText: {
        color: "#ffffff",
        fontSize: 13,
        fontWeight: "bold",
    },

    // Action Form (Inline Popups)
    actionForm: {
        backgroundColor: "#131924",
        borderWidth: 1.5,
        borderColor: "#FFA800",
        borderRadius: 16,
        padding: 14,
        marginBottom: 16,
        shadowColor: "#FFA800",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    formTitle: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 14,
        marginBottom: 10,
    },
    inputRow: {
        flexDirection: "row",
        gap: 8,
    },
    amountInput: {
        flex: 1,
        backgroundColor: "rgba(255,255,255,0.05)",
        borderWidth: 1,
        borderColor: "#20293d",
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
        color: "#fff",
        fontSize: 14,
    },
    goBtn: {
        backgroundColor: "#FFA800",
        paddingHorizontal: 16,
        borderRadius: 10,
        justifyContent: "center",
    },
    goBtnText: {
        color: "#000",
        fontWeight: "bold",
        fontSize: 13,
    },
    cancelBtn: {
        marginTop: 8,
        alignSelf: "center",
    },
    cancelText: {
        color: "rgba(255,255,255,0.4)",
        fontSize: 12,
    },

    // Bottom Transactions Dashboard Panel
    dashboardContainer: {
        backgroundColor: "#1E0507",
        borderWidth: 1,
        borderColor: "#4A0B0D",
        borderRadius: 24,
        padding: 16,
        flex: 1,
        marginTop: 10,
    },
    listHeaderRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginVertical: 12,
    },
    listHeaderLine: {
        flex: 1,
        height: 1,
        backgroundColor: "rgba(255, 255, 255, 0.15)",
    },
    listHeaderTitle: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "bold",
        marginHorizontal: 12,
        letterSpacing: 0.5,
    },
    pillRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    pillBordered: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.12)",
        backgroundColor: "rgba(255, 255, 255, 0.02)",
        marginRight: 10,
    },
    pillText: {
        color: "rgba(255, 255, 255, 0.75)",
        fontSize: 11,
        fontWeight: "500",
    },
    rounsitTab: {
        marginLeft: "auto",
        justifyContent: "center",
    },
    rounsitText: {
        color: "rgba(255, 255, 255, 0.6)",
        fontSize: 11,
        fontWeight: "500",
    },
    scrollFilters: {
        flexDirection: "row",
        marginVertical: 12,
    },
    filterTab: {
        marginRight: 16,
        paddingVertical: 4,
        justifyContent: "center",
    },
    filterTabActive: {
        backgroundColor: "rgba(255, 168, 0, 0.12)",
        paddingHorizontal: 8,
        borderRadius: 10,
    },
    filterTabText: {
        color: "rgba(255, 255, 255, 0.55)",
        fontSize: 12,
        fontWeight: "600",
    },
    filterTabTextActive: {
        color: "#FFA800",
        fontSize: 12,
        fontWeight: "700",
    },
    thirdRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginVertical: 10,
    },
    checkboxGroup: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    checkboxText: {
        color: "#FFA800",
        fontSize: 11,
        fontWeight: "600",
    },
    rightPillGroup: {
        flexDirection: "row",
        alignItems: "center",
    },
    miniPill: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.1)",
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 5,
    },
    miniPillText: {
        color: "rgba(255, 255, 255, 0.8)",
        fontSize: 10,
        fontWeight: "bold",
    },
    divider: {
        height: 1,
        backgroundColor: "rgba(255, 255, 255, 0.08)",
        marginVertical: 12,
    },
    txnList: {
        gap: 8,
    },
    txnItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 12,
        borderRadius: 12,
        backgroundColor: "#0F0203",
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.02)",
    },
    txnLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        flex: 1,
    },
    avatarContainer: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(255, 255, 255, 0.05)",
    },
    avatarText: {
        fontSize: 22,
    },
    txnInfo: {
        flex: 1,
    },
    txnTitle: {
        color: "#fff",
        fontSize: 13,
        fontWeight: "700",
    },
    txnSub: {
        color: "rgba(255, 255, 255, 0.4)",
        fontSize: 10,
        marginTop: 2,
    },
    txnRight: {
        alignItems: "flex-end",
        minWidth: 70,
    },
    statusText: {
        fontSize: 14,
        fontWeight: "bold",
    },
    statusTextSuccess: {
        color: "#22c55e",
    },
    statusTextError: {
        color: "#ef4444",
    },
});

// Winning/Result Screen Styles (Premium Look)
export const winningStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#070709" },
    gradient: { flex: 1 },
    scrollContent: {
        paddingHorizontal: 20,
        paddingVertical: 30,
        alignItems: "center",
    },

    // Confetti / Celebration Elements
    trophyWrapper: {
        width: 140,
        height: 140,
        borderRadius: 70,
        backgroundColor: "rgba(255,215,0,0.1)",
        borderWidth: 2.5,
        borderColor: "#FFD700",
        alignItems: "center",
        justifyContent: "center",
        marginVertical: 20,
        shadowColor: "#FFD700",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 15,
        elevation: 8,
    },
    trophyIcon: { fontSize: 64 },

    resultBadge: {
        borderRadius: 20,
        paddingHorizontal: 24,
        paddingVertical: 8,
        borderWidth: 1.5,
        marginVertical: 10,
    },
    resultBadgeText: { fontSize: 16, fontWeight: "900", letterSpacing: 2 },

    outcomeTitle: {
        fontSize: 32,
        fontWeight: "900",
        color: "#fff",
        letterSpacing: 1.5,
        textAlign: "center",
        marginTop: 10,
    },
    outcomeSubtitle: {
        fontSize: 14,
        color: "rgba(255,255,255,0.6)",
        textAlign: "center",
        marginTop: 6,
        marginHorizontal: 20,
    },

    // Prize Display
    prizeBox: {
        marginVertical: 24,
        alignItems: "center",
        paddingVertical: 16,
        paddingHorizontal: 40,
        borderRadius: 20,
        backgroundColor: "rgba(255,255,255,0.04)",
        borderWidth: 1,
        borderColor: "rgba(255,215,0,0.2)",
    },
    prizeLabel: {
        fontSize: 12,
        color: "rgba(255,255,255,0.5)",
        letterSpacing: 1,
    },
    prizeValue: { fontSize: 44, fontWeight: "900", marginTop: 6 },

    // Game Summary Card
    summaryCard: {
        width: "100%",
        borderRadius: 20,
        backgroundColor: "#111216",
        padding: 20,
        borderWidth: 1.5,
        borderColor: "rgba(255,255,255,0.08)",
        marginBottom: 30,
    },
    summaryTitle: {
        color: "#fff",
        fontSize: 15,
        fontWeight: "bold",
        letterSpacing: 1,
        marginBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(255,255,255,0.1)",
        paddingBottom: 10,
    },
    summaryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        paddingVertical: 8,
    },
    summaryLabel: { color: "rgba(255,255,255,0.5)", fontSize: 13 },
    summaryValue: { color: "#fff", fontSize: 14, fontWeight: "700" },

    // Call to action button
    ctaButton: {
        width: "100%",
        borderRadius: 25,
        overflow: "hidden",
        elevation: 6,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
    ctaGradient: { paddingVertical: 18, alignItems: "center" },
    ctaText: { fontSize: 17, fontWeight: "bold", letterSpacing: 1.5 },

    secondaryBtn: {
        marginTop: 15,
        paddingVertical: 12,
        width: "100%",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 25,
        borderWidth: 1.5,
        borderColor: "rgba(255,255,255,0.2)",
    },
    secondaryText: {
        color: "rgba(255,255,255,0.7)",
        fontSize: 15,
        fontWeight: "600",
    },
});

export const homeScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#000000", // Solid pitch black backing around container
        paddingTop: 20,
    },
    safeArea: {
        flex: 1,
    },
    headerWrapper: {
        width: "100%",
        height: 105,
        backgroundColor: "#000000",
        position: "relative",
        zIndex: 15,
    },
    headerGradient: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        height: 70,
        overflow: "hidden",
    },
    headerContent: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        zIndex: 10,
    },
    headerGlowBeam: {
        position: "absolute",
        bottom: 0,
        alignSelf: "center",
        width: 260,
        height: 48,
        borderTopLeftRadius: 130,
        borderTopRightRadius: 130,
        opacity: 0.28,
    },
    headerSparkle: {
        position: "absolute",
    },
    sparkleChar: {
        color: "#FFD700",
        fontSize: 10,
    },
    headerTitleContainer: {
        position: "absolute",
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1,
    },
    headerTitleText: {
        color: "#FFE8A3",
        fontSize: 22,
        fontWeight: "900",
        letterSpacing: 2.5,
        textShadowColor: "rgba(0, 0, 0, 0.85)",
        textShadowOffset: { width: 1.2, height: 1.8 },
        textShadowRadius: 3,
    },
    leftBadgeGear: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1.5,
        borderColor: "#FFD700",
        borderStyle: "dashed",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 1,
        elevation: 2,
    },
    leftBadgeInner: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: "#5E0004",
        borderWidth: 1,
        borderColor: "#FFD700",
        justifyContent: "center",
        alignItems: "center",
    },
    rightBadgeContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#5E0004",
        borderWidth: 1.5,
        borderColor: "#FFD700",
        borderRadius: 15,
        paddingLeft: 4,
        paddingRight: 10,
        height: 30,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1.5 },
        shadowOpacity: 0.4,
        shadowRadius: 2,
        elevation: 3,
    },
    rightBadgeIconCircle: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#FFD700",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#380002",
    },
    rightBadgeText: {
        color: "#FFD700",
        fontSize: 13,
        fontWeight: "900",
        textShadowColor: "rgba(0, 0, 0, 0.8)",
        textShadowOffset: { width: 0.8, height: 1 },
        textShadowRadius: 1.5,
        marginLeft: 6,
    },
    headerBottomCurveContainer: {
        position: "absolute",
        top: 70,
        left: 0,
        right: 0,
        height: 35,
        overflow: "hidden",
        zIndex: 5,
    },
    headerBottomCurveCover: {
        position: "absolute",
        top: -4970,
        left: "50%",
        width: 5000,
        height: 5000,
        marginLeft: -2500,
        backgroundColor: "#6E0003",
        borderRadius: 2500,
    },
    headerBottomCurveLine: {
        position: "absolute",
        top: -4968,
        left: "50%",
        width: 5000,
        height: 5000,
        marginLeft: -2500,
        borderRadius: 2500,
    },
    body: {
        flex: 1,
        paddingHorizontal: 12,
        paddingTop: 14,
        backgroundColor: "#000000",
        paddingBottom: 40,
    },
    outerBoardFrame: {
        flex: 1,
        borderWidth: 3.5,
        borderColor: "#B8860B", // Thick dark gold border
        borderRadius: 24,
        backgroundColor: "#000000",
        padding: 6,
    },
    innerBoardFrame: {
        flex: 1,
        borderWidth: 1.5,
        borderColor: "#DAA520", // Thin gold border inside
        borderRadius: 18,
        backgroundColor: "#050302", // Deep brown-black tone
        padding: 10,
    },
    boardHeaderRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#1E1E1E",
        borderWidth: 1,
        borderColor: "#333",
        borderRadius: 12,
        paddingVertical: 12,
        marginBottom: 16,
        position: "relative",
    },
    boardHeaderLeftGroup: {
        position: "absolute",
        left: 14,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    boardHeaderTitle: {
        color: "#DAA520",
        fontSize: 13,
        fontWeight: "900",
        letterSpacing: 1.2,
    },
    boardHeaderRightGroup: {
        position: "absolute",
        right: 14,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    scrollContent: {
        paddingBottom: 20,
    },
    cardOuter: {
        marginBottom: 12,
    },
    cardGradient: {
        borderRadius: 16,
    },
    cardTouchRow: {
        flexDirection: "row",
        padding: 10,
        alignItems: "center",
    },
    medalCardOuterFrame: {
        borderRadius: 16,
        overflow: "hidden",
        borderWidth: 1.5,
        borderColor: "#DAA520",
    },
    medalCardContainer: {
        width: 78,
        height: 78,
        borderRadius: 14,
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
        overflow: "hidden",
        backgroundColor: "#0A0A0A",
    },
    sunburstContainer: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: "center",
        alignItems: "center",
        opacity: 0.22,
    },
    sunburstRay: {
        position: "absolute",
        width: 1.2,
        height: 100,
        backgroundColor: "rgba(255, 215, 0, 0.22)",
    },
    badgeImage: {
        width: 78,
        height: 78,
        position: "absolute",
    },
    rosetteContainer: {
        width: 64,
        height: 64,
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
    },
    rosettePetal: {
        position: "absolute",
        width: 46,
        height: 46,
        borderRadius: 2,
    },
    rosetteOuterRing: {
        position: "absolute",
        width: 48,
        height: 48,
        borderRadius: 24,
        borderWidth: 1.5,
        borderColor: "#8A640F",
        backgroundColor: "#DAA520",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1.5 },
        shadowOpacity: 0.4,
        shadowRadius: 2,
        elevation: 3,
    },
    rosetteMidRing: {
        width: 42,
        height: 42,
        borderRadius: 21,
        borderWidth: 2,
        borderColor: "#FFF5C2",
        backgroundColor: "#AA820A",
        justifyContent: "center",
        alignItems: "center",
    },
    rosetteInnerRing: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: 1.2,
        borderColor: "#4A3504",
        backgroundColor: "#DAA520",
        justifyContent: "center",
        alignItems: "center",
    },
    rosetteFace: {
        width: 30,
        height: 30,
        borderRadius: 15,
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
        overflow: "hidden",
    },
    ribbonLeftTail: {
        position: "absolute",
        bottom: -14,
        left: 24,
        width: 9,
        height: 24,
        transform: [{ rotate: "-12deg" }],
        overflow: "hidden",
        borderRadius: 1,
    },
    ribbonRightTail: {
        position: "absolute",
        bottom: -14,
        right: 24,
        width: 9,
        height: 24,
        transform: [{ rotate: "12deg" }],
        overflow: "hidden",
        borderRadius: 1,
    },
    ribbonGradient: {
        width: "100%",
        height: "100%",
        borderWidth: 0.8,
        borderColor: "#AA820A",
    },
    ribbonCutout: {
        position: "absolute",
        bottom: -5,
        left: -0.5,
        width: 9,
        height: 9,
        transform: [{ rotate: "45deg" }],
    },
    medalStar: {
        position: "absolute",
        color: "#FFF5C2",
        fontSize: 4,
        opacity: 0.95,
    },
    glassShineTopOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        height: 15,
        backgroundColor: "rgba(255,255,255,0.22)",
        borderBottomLeftRadius: 7.5,
        borderBottomRightRadius: 7.5,
    },
    medalRewardText: {
        color: "#FFF5C2",
        fontWeight: "900",
        fontSize: 10,
        textShadowColor: "#000",
        textShadowRadius: 2,
        zIndex: 10,
    },
    infoSection: {
        flex: 1,
        paddingLeft: 12,
        justifyContent: "space-between",
        height: 78,
    },
    titleRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
    },
    gameName: {
        fontSize: 15,
        fontWeight: "bold",
        color: "#FFFFFF",
        letterSpacing: 0.3,
    },
    gameSubTitle: {
        fontSize: 12,
        color: "#888888",
        fontWeight: "700",
        marginTop: 1,
    },
    actionBadge: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: "#2D2D2D",
        alignItems: "center",
        justifyContent: "center",
    },
    detailsRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 8,
    },
    detailsTextLeft: {
        color: "rgba(255, 255, 255, 0.7)",
        fontSize: 13,
        fontWeight: "bold",
    },
    goldMultiplierText: {
        color: "#FFD700",
        fontWeight: "900",
    },
    detailsTextRight: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "900",
    },
    footerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 4,
    },
    footerTextLeft: {
        color: "#DAA520",
        fontSize: 12,
        fontWeight: "900",
    },
    footerTextRight: {
        color: "#DAA520",
        fontSize: 12,
        fontWeight: "900",
    },
    bottomTab: {
        alignSelf: "center",
        backgroundColor: "#000000",
        borderWidth: 2,
        borderColor: "#B8860B",
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        paddingHorizontal: 24,
        paddingVertical: 6,
        position: "absolute",
        bottom: 0,
        zIndex: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        borderBottomWidth: 0,
    },
    closeButton: {
        width: 26,
        height: 26,
        borderRadius: 13,
        backgroundColor: "#DAA520",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#DAA520",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.6,
        shadowRadius: 3,
    },
});
